import type { Metadata } from "next";
import "./globals.css";
import { ubuntu, outfit} from "./fonts";
import Header from "@/components/header";
import ThemeProvider from "@/context/theme-provider";
import { Footer } from "@/components/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="pt-br">
      <body className={`${outfit.variable} ${ubuntu.variable} antialiased scroll-smooth`}>
        <ThemeProvider>
          <Header />
          {children}
          <Footer/>
        </ThemeProvider>
      </body>
    </html>
  );
}
